# Build stage
FROM node:14 AS build

WORKDIR /client

# Copy package.json and package-lock.json first to leverage Docker caching
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the client code
COPY . .

# Build the React app
RUN npm run build

# Check the build output
RUN ls -la /client/dist

# Production stage
FROM nginx:alpine
COPY --from=build /client/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
